// Author-time car generator (Variant B — docs/plans/cars.md). Parses each cars/<svg> named in
// js/car-registry.js and writes the committed, static js/cars-data.js that the game imports
// synchronously. Run after adding/editing a car:  npm run gen:cars
//
// Zero-dep: Node built-ins + regex (the car SVGs are flat — no groups/transforms). The pure
// parseCarSvg() is exported for unit testing; the file only regenerates when run directly.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { CAR_REGISTRY } from '../js/car-registry.js';
import { driveForRatings } from '../js/car-stats.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');

// Normalise a colour to the project's house style (bare `black`/`#000` → #222222).
const normColour = (c) => {
  if (!c) return null;
  const v = c.trim().toLowerCase();
  return (v === 'black' || v === '#000' || v === '#000000') ? '#222222' : c.trim();
};

// Pure: parse a car SVG's text into render pieces per the convention (see docs/plans/cars.md).
//   • stroke-only <path> = body silhouette; if several, the LONGEST `d` is the body, the rest
//     become `lines` (stroke-only panel paths).
//   • filled <path> (fill ≠ none) = a detail { c: fill, d }, kept in document order (z-order).
//   • viewBox (or width/height) → vw/vh.
// Returns { vw, vh, path, stroke, details, lines }.
export const parseCarSvg = (svg) => {
  const vb = svg.match(/viewBox="([^"]*)"/);
  let vw, vh;
  if (vb) { const p = vb[1].trim().split(/\s+/).map(Number); vw = p[2]; vh = p[3]; }
  if (!vw || !vh) {
    vw = Number((svg.match(/\bwidth="([\d.]+)"/) || [])[1]);
    vh = Number((svg.match(/\bheight="([\d.]+)"/) || [])[1]);
  }

  const details = [];
  const strokes = [];   // { d } for every stroke-only path
  for (const m of svg.matchAll(/<path\b([^>]*?)\/?>/gs)) {
    const attrs  = m[1];
    const d      = (attrs.match(/\bd="([^"]*)"/)      || [])[1];
    if (!d) continue;
    const fill   = (attrs.match(/\bfill="([^"]*)"/)   || [])[1];
    const stroke = (attrs.match(/\bstroke="([^"]*)"/) || [])[1];
    const hasFill = fill && fill.toLowerCase() !== 'none';
    if (hasFill)      details.push({ c: normColour(fill), d });
    else if (stroke)  strokes.push({ d, stroke });
  }
  if (!strokes.length) throw new Error('no stroke (body) path found in SVG');

  // Longest `d` = the enclosing body silhouette; the shorter stroke paths are panel lines.
  strokes.sort((a, b) => b.d.length - a.d.length);
  const body  = strokes[0];
  const lines = strokes.slice(1).map(s => s.d);
  return { vw, vh, path: body.d, stroke: normColour(body.stroke), details, lines };
};

// Build the descriptor the game uses: rating-derived drive + feel, plus the parsed geometry.
export const buildCarData = (entry, svgText) => {
  const g = parseCarSvg(svgText);
  const car = {
    id:     entry.id,
    name:   entry.name,
    len:    entry.len ?? 78,
    body:   entry.body,
    stroke: entry.stroke ?? g.stroke ?? '#222222',
    vw:     g.vw,
    vh:     g.vh,
    flip:   entry.flip ?? false,
    drive:  { ...driveForRatings(entry.ratings), ...(entry.feel || {}) },
    details: g.details,
    ...(g.lines.length ? { lines: g.lines } : {}),
    path:   g.path,
  };
  return car;
};

// Pretty-print one car as source (stable key order; compact detail rows).
const emitCar = (c) => {
  const parts = [
    `    id: ${JSON.stringify(c.id)}, name: ${JSON.stringify(c.name)}, len: ${c.len},`,
    `    body: ${JSON.stringify(c.body)}, stroke: ${JSON.stringify(c.stroke)}, vw: ${c.vw}, vh: ${c.vh}, flip: ${c.flip},`,
    `    drive: ${JSON.stringify(c.drive)},`,
    `    details: [`,
    ...c.details.map(d => `      { c: ${JSON.stringify(d.c)}, d: ${JSON.stringify(d.d)} },`),
    `    ],`,
    ...(c.lines ? [`    lines: ${JSON.stringify(c.lines)},`] : []),
    `    path: ${JSON.stringify(c.path)},`,
  ];
  return `  {\n${parts.join('\n')}\n  },`;
};

const generate = () => {
  const cars = CAR_REGISTRY.map((entry) => {
    const svgText = readFileSync(join(ROOT, 'cars', entry.svg), 'utf8');
    return buildCarData(entry, svgText);
  });
  const out =
    '// GENERATED by scripts/gen-cars.js from cars/*.svg + js/car-registry.js — DO NOT EDIT.\n' +
    '// Rebuild with:  npm run gen:cars\n' +
    'export const GENERATED_CARS = [\n' +
    cars.map(emitCar).join('\n') + '\n' +
    '];\n';
  writeFileSync(join(ROOT, 'js', 'cars-data.js'), out);
  console.log(`gen-cars: wrote js/cars-data.js (${cars.length} car${cars.length === 1 ? '' : 's'})`);
};

// Only regenerate when run directly (not when imported by a test).
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) generate();
